name: test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v4
      - run: cd hjson && cargo build
      - run: cd hjson_cli && cargo build
      - run: cd hjson_tests && cargo test
      - run: cd hjson && cargo doc
