name: test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - run: cd hjson && cargo build --release
      - run: cd hjson_cli && cargo build --release
      - run: cargo test -- --nocapture
      - run: cd hjson && cargo doc
